version: 1.3.0.{build}-{branch}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
platform: x86
shallow_clone: true
clone_depth: 3
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}.{build}'
  assembly_file_version: '{version}.{build}'
  assembly_informational_version: '{version}.{build}-{branch}'
build:
  project: Crystal-Alien-Map-Maker.sln
  verbosity: minimal